/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tallerautomotriz.ArchivoVehiculos;
import tallerautomotriz.Repuesto;
import tallerautomotriz.ServicioTecnico;
import tallerautomotriz.Taller;
import tallerautomotriz.Vehiculo;

/**
 *
 * @author Roberson Constante
 */
public class frmPrincipal extends javax.swing.JFrame {

    ArchivoVehiculos arcArchivoVehiculo = new ArchivoVehiculos();
    ServicioTecnico arcServicio = new ServicioTecnico();
    ArrayList<Vehiculo> lista = new ArrayList<>();
    ArrayList<Taller> listaT = new ArrayList<>();
    ArrayList<Repuesto> listaR = new ArrayList<>();
     ArrayList<Repuesto> listaCarrito = new ArrayList<>();
    Taller t1 = new Taller();
    Vehiculo v1 = new Vehiculo();
    Vehiculo v2= new Vehiculo();
    public frmPrincipal() {
        initComponents();
        pnlDetalleVehiculo.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        pnlDetalleVehiculo.setVisible(true);
        //mostrarDatos();
        calcularPrecio();
    }
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    public void mostrarDatos(){
        modelo.addColumn("CHASIS");
        modelo.addColumn("MODELO");
        modelo.addColumn("MARCA");
        modelo.addColumn("PRECIO");
        jtblVehiculos.setModel(modelo);
        String [] datos = new String [4];
        lista = arcArchivoVehiculo.obtenerVehiculo();
        Iterator it = lista.iterator();
        while(it.hasNext()){
            v1 = (Vehiculo) it.next();
            datos[0] = v1.getChasis();
            datos[1] = v1.getModelo();
            datos[2] = v1.getMarca();
            datos[3] = String.valueOf(v1.getPrecio());
            modelo.addRow(datos);
        }
    }
     public void mostrarDatosTalleres(){   
        modelo2.addColumn("NOMBRE");
        modelo2.addColumn("ESPECIALIDAD");
        modelo2.addColumn("UBICACION");
        jtblListaTalleres.setModel(modelo2);
        String [] datos = new String [3];
        listaT = arcServicio.obtenerTaller();
        Iterator it = listaT.iterator();
        while(it.hasNext()){
            t1 = (Taller) it.next();
            datos[0] = t1.getNombre();
            datos[1] = t1.getEspecialidad();
            datos[2] = t1.getUbicacion();
            modelo2.addRow(datos);
        }
    }
    
    public void mostrarV(){
        lista = arcArchivoVehiculo.buscarVehiculo(txtBuscaMarcaModelo.getText());
        Iterator it = lista.iterator();
        String [] datos = new String [4];
        while(it.hasNext()){
            v1 = (Vehiculo) it.next();
            datos[0] = v1.getChasis();
            datos[1] = v1.getModelo();
            datos[2] = v1.getMarca();
            datos[3] = String.valueOf(v1.getPrecio());
            modelo.addRow(datos);
        }
    }
    
    public void calcularPrecio(){
        String color = cmbNuevoColor.getSelectedItem().toString();
        String trasmision = cmbNuevoTipoTransmision.getSelectedItem().toString();
        String tapiceria = cmbNuevaTapiceria.getSelectedItem().toString();
        String llanta = cmbNuevaTipoLLantas.getSelectedItem().toString();
        String aros=cmbNuevoTipoAros.getSelectedItem().toString();
        if(!color.equals(v1.getColor())){
            v1.setPrecio(v1.getPrecio()+50);
        }
        if(trasmision!=v1.getTipoTransmision()){
            v1.setPrecio(v1.getPrecio()+500);
        }
        if(llanta!=v1.getTipoLLanta()){
            v1.setPrecio(v1.getPrecio()+120);
        }
        if(aros!=v1.getTipoAros()){
            v1.setPrecio(v1.getPrecio()+100);
        }
        txtPrecio.setText(String.valueOf(v1.getPrecio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelComprar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscaMarcaModelo = new javax.swing.JTextField();
        btnBuscarVehiculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVehiculos = new javax.swing.JTable();
        pnlDetalleVehiculo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblValorMarca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorModelo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblValorTipoMotor = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblValorCilindraje = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblValorNumeroPuertas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblValorAnoFabricacion = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblValorPlaca = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbNuevoTipoAros = new javax.swing.JComboBox<String>();
        cmbNuevaTipoLLantas = new javax.swing.JComboBox<String>();
        cmbNuevaTapiceria = new javax.swing.JComboBox<String>();
        cmbNuevoTipoTransmision = new javax.swing.JComboBox<String>();
        cmbNuevoColor = new javax.swing.JComboBox<String>();
        txtPrecio = new javax.swing.JTextField();
        btnComprarAuto = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        lblValorChasis = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtTipoMotor = new javax.swing.JTextField();
        txtChasis = new javax.swing.JTextField();
        txtCilindro = new javax.swing.JTextField();
        txtNumeroP = new javax.swing.JTextField();
        txtFabricacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        jPanelVender = new javax.swing.JPanel();
        pnlFormularioVenta = new javax.swing.JPanel();
        lblVentaMarca = new javax.swing.JLabel();
        lblVentaModelo = new javax.swing.JLabel();
        lblVentaTipoMotor = new javax.swing.JLabel();
        lblVentaCilindraje = new javax.swing.JLabel();
        lblVentaPuertas = new javax.swing.JLabel();
        lblVentaAnioFabricacion = new javax.swing.JLabel();
        lblVentaPlaca = new javax.swing.JLabel();
        btnComprarAuto1 = new javax.swing.JButton();
        lblVentaChasis = new javax.swing.JLabel();
        txtVentaMarca = new javax.swing.JTextField();
        txtVentaModelo = new javax.swing.JTextField();
        txtVentaPlaca = new javax.swing.JTextField();
        txtVentaMotor = new javax.swing.JTextField();
        txtVentaChasis = new javax.swing.JTextField();
        txtVentaCilindraje = new javax.swing.JTextField();
        txtVentaPuertas = new javax.swing.JTextField();
        txtVentaAnioFab = new javax.swing.JTextField();
        lblVentaColor = new javax.swing.JLabel();
        lblVentaTransmision = new javax.swing.JLabel();
        lblVentaTapiceria = new javax.swing.JLabel();
        lblVentaLlantas = new javax.swing.JLabel();
        lblVentaAros = new javax.swing.JLabel();
        lblVentaPrecio = new javax.swing.JLabel();
        txtVentaColor = new javax.swing.JTextField();
        txtVentaTransmision = new javax.swing.JTextField();
        txtVentaTapiceria = new javax.swing.JTextField();
        txtVentaLlantas = new javax.swing.JTextField();
        txtVentaAros = new javax.swing.JTextField();
        txtVentaPrecio = new javax.swing.JTextField();
        txtVentaMatricula = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblPrecioOfrecidoConcecionaria = new javax.swing.JLabel();
        lblPrecioSugeridoVenta = new javax.swing.JLabel();
        lblPrecioCliente = new javax.swing.JLabel();
        btnAceptarOferta = new javax.swing.JButton();
        btnNuevaOferta = new javax.swing.JButton();
        txtPrecioOfertadoCliente = new javax.swing.JTextField();
        btnCancelarVenta = new javax.swing.JButton();
        txtPrecioAdmin = new javax.swing.JTextField();
        jPanelTalleres = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarTalleres = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtblListaTalleres = new javax.swing.JTable();
        jPanelRepuestos = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarRepuestos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblRepuestos = new javax.swing.JTable();
        btnMr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblPrecioRepuesto = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblNombreR = new javax.swing.JLabel();
        spnCantidadRepuestos = new javax.swing.JSpinner();
        lblCantidadRepuesto = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblCarritoRespuestos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lblMarcaRepuesto = new javax.swing.JLabel();
        lblMarcaRep = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        lblPrecioRep = new javax.swing.JLabel();
        btnEliminarRep = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Comprar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Vehículo"));

        jLabel1.setText("Escriba la Marca de vehículo que desea comprar:");

        btnBuscarVehiculo.setText("Buscar");
        btnBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculoActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscaMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnBuscarVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarVehiculo)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblVehiculos);

        pnlDetalleVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Vehículo"));

        jLabel2.setText("Marca");

        jLabel9.setText("Modelo");

        jLabel11.setText("Tipo de motor");

        jLabel13.setText("Cilindraje");

        jLabel15.setText("Número de Puertas ");

        jLabel17.setText("Año de Fabricación");

        jLabel22.setText("Placa");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Características Personalizables"));

        jLabel3.setText("Color");

        jLabel4.setText("Tipo de transmisión");

        jLabel5.setText("Tapicería");

        jLabel7.setText("Tipo de LLantas");

        jLabel8.setText("Tipo de Aros");

        jLabel19.setText("Precio");

        jLabel20.setText("$");

        cmbNuevoTipoAros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Niquelados", "Estándar", "Aluminio" }));
        cmbNuevoTipoAros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuevoTipoArosActionPerformed(evt);
            }
        });

        cmbNuevaTipoLLantas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Llantas de carrera", "Llantas todo terreno", "Llantas estándar" }));
        cmbNuevaTipoLLantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuevaTipoLLantasActionPerformed(evt);
            }
        });

        cmbNuevaTapiceria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuero", "Tela", "Fibras" }));
        cmbNuevaTapiceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuevaTapiceriaActionPerformed(evt);
            }
        });

        cmbNuevoTipoTransmision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automática", "Manual" }));
        cmbNuevoTipoTransmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuevoTipoTransmisionActionPerformed(evt);
            }
        });

        cmbNuevoColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amarillo", "Azul", "Blanco", "Gris", "Rojo", "Vino", "Negro", " ", " " }));
        cmbNuevoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuevoColorActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbNuevoColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbNuevoTipoTransmision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbNuevaTapiceria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbNuevaTipoLLantas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbNuevoTipoAros, 0, 183, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoTipoTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevaTapiceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevaTipoLLantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoTipoAros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnComprarAuto.setText("Comprar Vehículo");
        btnComprarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAutoActionPerformed(evt);
            }
        });

        jLabel24.setText("Chasis");

        javax.swing.GroupLayout pnlDetalleVehiculoLayout = new javax.swing.GroupLayout(pnlDetalleVehiculo);
        pnlDetalleVehiculo.setLayout(pnlDetalleVehiculoLayout);
        pnlDetalleVehiculoLayout.setHorizontalGroup(
            pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel11))
                                .addGap(180, 180, 180)
                                .addComponent(lblValorAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblValorTipoMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorNumeroPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorChasis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addGap(93, 93, 93)
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(320, Short.MAX_VALUE))
                    .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleVehiculoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFabricacion, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtTipoMotor)
                                    .addComponent(txtChasis)
                                    .addComponent(txtCilindro)
                                    .addComponent(txtNumeroP))
                                .addGap(121, 121, 121)))
                        .addGap(0, 241, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleVehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprarAuto)
                .addGap(202, 202, 202))
        );
        pnlDetalleVehiculoLayout.setVerticalGroup(
            pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleVehiculoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValorPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(lblValorTipoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTipoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorChasis, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblValorCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorNumeroPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarAuto)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Resultados");

        jLabel10.setText("Pare ver mayor detalles seleccionar la fila del vehículo");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComprarLayout = new javax.swing.GroupLayout(jPanelComprar);
        jPanelComprar.setLayout(jPanelComprarLayout);
        jPanelComprarLayout.setHorizontalGroup(
            jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarLayout.createSequentialGroup()
                .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComprarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)))
                    .addGroup(jPanelComprarLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnSeleccionar)))
                .addGap(18, 18, 18)
                .addComponent(pnlDetalleVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComprarLayout.setVerticalGroup(
            jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetalleVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelComprarLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeleccionar)))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelComprar, "card2");

        pnlFormularioVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vehiculo"));

        lblVentaMarca.setText("Marca");

        lblVentaModelo.setText("Modelo");

        lblVentaTipoMotor.setText("Tipo de motor");

        lblVentaCilindraje.setText("Cilindraje");

        lblVentaPuertas.setText("Número de Puertas ");

        lblVentaAnioFabricacion.setText("Color interior");

        lblVentaPlaca.setText("Placa");

        btnComprarAuto1.setText("Registrar Vehiculo Para Venta");
        btnComprarAuto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAuto1ActionPerformed(evt);
            }
        });

        lblVentaChasis.setText("Chasis");

        txtVentaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentaMarcaActionPerformed(evt);
            }
        });

        lblVentaColor.setText("Color");

        lblVentaTransmision.setText("Tipo de transmisión");

        lblVentaTapiceria.setText("Tapicería");

        lblVentaLlantas.setText("Tipo de LLantas");

        lblVentaAros.setText("Tipo de Aros");

        lblVentaPrecio.setText("Precio");

        jLabel23.setText("Año Fabricación");

        javax.swing.GroupLayout pnlFormularioVentaLayout = new javax.swing.GroupLayout(pnlFormularioVenta);
        pnlFormularioVenta.setLayout(pnlFormularioVentaLayout);
        pnlFormularioVentaLayout.setHorizontalGroup(
            pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                        .addComponent(lblVentaLlantas)
                        .addGap(0, 529, Short.MAX_VALUE))
                    .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                        .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnComprarAuto1))
                            .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVentaMarca)
                                    .addComponent(lblVentaModelo)
                                    .addComponent(lblVentaPlaca)
                                    .addComponent(lblVentaTipoMotor)
                                    .addComponent(lblVentaChasis)
                                    .addComponent(lblVentaCilindraje)
                                    .addComponent(lblVentaPuertas)
                                    .addComponent(lblVentaAnioFabricacion)
                                    .addComponent(lblVentaAros)
                                    .addComponent(lblVentaColor)
                                    .addComponent(lblVentaTransmision)
                                    .addComponent(lblVentaTapiceria)
                                    .addComponent(lblVentaPrecio)
                                    .addComponent(jLabel23))
                                .addGap(87, 87, 87)
                                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVentaMarca)
                                    .addComponent(txtVentaModelo)
                                    .addComponent(txtVentaPlaca)
                                    .addComponent(txtVentaMotor)
                                    .addComponent(txtVentaChasis)
                                    .addComponent(txtVentaCilindraje)
                                    .addComponent(txtVentaPuertas)
                                    .addComponent(txtVentaAnioFab)
                                    .addComponent(txtVentaColor)
                                    .addComponent(txtVentaTransmision)
                                    .addComponent(txtVentaTapiceria)
                                    .addComponent(txtVentaLlantas)
                                    .addComponent(txtVentaAros)
                                    .addComponent(txtVentaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(txtVentaMatricula))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlFormularioVentaLayout.setVerticalGroup(
            pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioVentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtVentaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVentaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaModelo)
                    .addComponent(txtVentaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaPlaca)
                    .addComponent(txtVentaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaTipoMotor)
                    .addComponent(txtVentaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaChasis)
                    .addComponent(txtVentaChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVentaCilindraje)
                    .addComponent(txtVentaCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaPuertas)
                    .addComponent(txtVentaPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaAnioFabricacion)
                    .addComponent(txtVentaAnioFab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaColor)
                    .addComponent(txtVentaColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaTransmision)
                    .addComponent(txtVentaTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaTapiceria)
                    .addComponent(txtVentaTapiceria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaLlantas)
                    .addComponent(txtVentaLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaAros)
                    .addComponent(txtVentaAros, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVentaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVentaPrecio)
                    .addComponent(txtVentaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnComprarAuto1))
        );

        lblPrecioOfrecidoConcecionaria.setText("Precio Estimado del vehiculo:");

        lblPrecioCliente.setText("Precio Ofrecido Por el cliente:");

        btnAceptarOferta.setText("Aceptar");
        btnAceptarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarOfertaActionPerformed(evt);
            }
        });

        btnNuevaOferta.setText("Ofertar");
        btnNuevaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaOfertaActionPerformed(evt);
            }
        });

        txtPrecioOfertadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioOfertadoClienteActionPerformed(evt);
            }
        });

        btnCancelarVenta.setText("Cancelar");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioCliente)
                            .addComponent(lblPrecioOfrecidoConcecionaria))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioOfertadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtPrecioAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecioSugeridoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAceptarOferta)
                        .addGap(30, 30, 30)
                        .addComponent(btnNuevaOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnCancelarVenta)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecioOfrecidoConcecionaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPrecioSugeridoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioCliente)
                    .addComponent(txtPrecioOfertadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarOferta)
                    .addComponent(btnNuevaOferta)
                    .addComponent(btnCancelarVenta)))
        );

        javax.swing.GroupLayout jPanelVenderLayout = new javax.swing.GroupLayout(jPanelVender);
        jPanelVender.setLayout(jPanelVenderLayout);
        jPanelVenderLayout.setHorizontalGroup(
            jPanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormularioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanelVenderLayout.setVerticalGroup(
            jPanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenderLayout.createSequentialGroup()
                .addGroup(jPanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVenderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVenderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlFormularioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelVender, "card3");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Talleres"));

        jLabel12.setText("Listar Talleres:");

        txtBuscarTalleres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarTalleresActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar");

        jtblListaTalleres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jtblListaTalleres);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addComponent(txtBuscarTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addGap(38, 38, 38))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtBuscarTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanelTalleresLayout = new javax.swing.GroupLayout(jPanelTalleres);
        jPanelTalleres.setLayout(jPanelTalleresLayout);
        jPanelTalleresLayout.setHorizontalGroup(
            jPanelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );
        jPanelTalleresLayout.setVerticalGroup(
            jPanelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(694, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTalleres, "card4");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Repuestos"));

        jLabel14.setText("Buscar Repuestos");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblRepuestos);

        btnMr.setText("Mostrar Todo");
        btnMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMr)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(57, 57, 57)
                        .addComponent(txtBuscarRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBuscarRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnMr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setText("Precio");

        jLabel18.setText("Nombre:");

        lblCantidadRepuesto.setText("Cantidad:");

        jtblCarritoRespuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtblCarritoRespuestos);

        jButton4.setText("Comprar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblMarcaRepuesto.setText("Marca:");

        jButton5.setText("Añadir A Carrito");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnEliminarRep.setText("Eliminar");
        btnEliminarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(lblMarcaRepuesto))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(lblCantidadRepuesto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spnCantidadRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblMarcaRep, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblPrecioRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(lblPrecioRep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(30, 30, 30)
                                .addComponent(btnEliminarRep)))
                        .addGap(54, 54, 54)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(lblNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCantidadRepuesto)
                                .addComponent(spnCantidadRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarcaRepuesto)
                            .addComponent(lblPrecioRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMarcaRep, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(lblPrecioRep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(btnEliminarRep)))
        );

        javax.swing.GroupLayout jPanelRepuestosLayout = new javax.swing.GroupLayout(jPanelRepuestos);
        jPanelRepuestos.setLayout(jPanelRepuestosLayout);
        jPanelRepuestosLayout.setHorizontalGroup(
            jPanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanelRepuestosLayout.setVerticalGroup(
            jPanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(645, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelRepuestos, "card5");

        jMenu1.setText("Vehículos ");

        Comprar.setText("Compra");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        jMenu1.add(Comprar);

        jMenuItem1.setText("Venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Servicio Técnico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Respuestos");

        jMenuItem4.setText("compra de Repuestos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
       jPanelVender.setVisible(false);
       jPanelTalleres.setVisible(false);
       jPanelComprar.setVisible(true);
       jPanelRepuestos.setVisible(false);
       mostrarDatos();
       
    }//GEN-LAST:event_ComprarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lblValorMarca.setText("");
        lblValorModelo.setText("");
        lblValorPlaca.setText("");
        lblValorTipoMotor.setText("");
        lblValorChasis.setText("");
        lblValorCilindraje.setText("");
        lblValorNumeroPuertas.setText("");
        lblValorAnoFabricacion.setText("");       
        pnlDetalleVehiculo.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculoActionPerformed
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
         pnlDetalleVehiculo.setVisible(true);
         arcArchivoVehiculo.buscarVehiculo(txtBuscaMarcaModelo.getText());
         mostrarV();      
    }//GEN-LAST:event_btnBuscarVehiculoActionPerformed

    private void btnComprarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAutoActionPerformed
        new frmDatosPago().setVisible(true);
    }//GEN-LAST:event_btnComprarAutoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       jPanelVender.setVisible(false);
       jPanelTalleres.setVisible(false);
       jPanelComprar.setVisible(false);
       jPanelRepuestos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnComprarAuto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAuto1ActionPerformed
        // TODO add your handling code here:
        v2.setMarca(txtVentaMarca.getText());
        v2.setModelo(txtVentaModelo.getText());
        v2.setPlaca(txtVentaPlaca.getText());
        v2.setTipoMotor(txtVentaMotor.getText());
        v2.setChasis(txtVentaChasis.getText());
        v2.setCilindraje(Integer.parseInt(txtVentaCilindraje.getText()));
        v2.setNumeroPuerta(Integer.parseInt(txtVentaPuertas.getText()));
        v2.setColor(txtVentaColor.getText());
        v2.setTipoTransmision(txtVentaTransmision.getText());
        v2.setMaterialInterior(txtVentaTapiceria.getText());
        v2.setTipoLLanta(txtVentaLlantas.getText());
        v2.setTipoAros(txtVentaAros.getText());
        v2.setPrecio(Float.parseFloat(txtVentaPrecio.getText()));
        v2.setAñoMatricula(Integer.parseInt(txtVentaMatricula.getText()));
        v2.setTipoVehiculo(null);
        v2.setDisponibilidad(true);
        float precio;
        switch(v2.getAñoFabricacion()){
            case 2015:
            case 2016:
            case 2017:
                if(v2.getCilindraje()>4){
                    precio=4000;
                }
                else{
                    precio=1000;
                }
                break;
            case 2018:
            case 2019:
            case 2020:
            case 2021:
                if(v2.getCilindraje()>4){
                    precio=8000;
                }
                else{
                    precio=5000;
                }
                break;
            default:
                precio=1000;
                break;
        }
        txtPrecioAdmin.setText(String.valueOf(precio));
        v2.setPrecio(precio);
        
    }//GEN-LAST:event_btnComprarAuto1ActionPerformed

    private void txtVentaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentaMarcaActionPerformed

    private void btnAceptarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarOfertaActionPerformed
        // TODO add your handling code here:
        if(v2.getMarca()==null || v2.getPlaca()==null || v2.getTipoTransmision()==null ){
            JOptionPane.showMessageDialog(null, "Llenar todos los campos");
        }
        else{
            arcArchivoVehiculo.adicionarVehiculo(v2);
            JOptionPane.showMessageDialog(null, "Felicidades Vendiste tu vehiculo!!! ");
            
        }
        
    }//GEN-LAST:event_btnAceptarOfertaActionPerformed

    private void btnNuevaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaOfertaActionPerformed
        // TODO add your handling code here:
        float a = Float.parseFloat(txtPrecioAdmin.getText())+500;
        float b = Float.parseFloat(txtPrecioOfertadoCliente.getText());
        
        if(a<b){
            JOptionPane.showMessageDialog(null, "Tu oferta ha sido rechazada sobrepasa nuestro estimado de "+a);
        }
        else{
            arcArchivoVehiculo.adicionarVehiculo(v2);
            JOptionPane.showMessageDialog(null, "Felicidades Vendiste tu vehiculo!!! ");
        }
    }//GEN-LAST:event_btnNuevaOfertaActionPerformed

    private void txtPrecioOfertadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioOfertadoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioOfertadoClienteActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        // TODO add your handling code here:
        txtVentaMarca.setText("");
        txtVentaModelo.setText("");
        txtVentaPlaca.setText("");
        txtVentaMotor.setText("");
        txtVentaChasis.setText("");
        txtVentaCilindraje.setText("");
        txtVentaPuertas.setText("");
        txtVentaColor.setText("");
        txtVentaTransmision.setText("");
        txtVentaTapiceria.setText("");
        txtVentaLlantas.setText("");
        txtVentaAros.setText("");
        txtVentaPrecio.setText("");
        txtVentaMatricula.setText("");
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanelComprar.setVisible(false);
        jPanelTalleres.setVisible(false);
        jPanelVender.setVisible(true);
        jPanelRepuestos.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtBuscarTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarTalleresActionPerformed
        
    }//GEN-LAST:event_txtBuscarTalleresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         jPanelVender.setVisible(false);
       jPanelTalleres.setVisible(true);
       jPanelComprar.setVisible(false);
       jPanelRepuestos.setVisible(false);
       mostrarDatosTalleres();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila=jtblVehiculos.getSelectedRow();
        if(fila>=0){
            String a = String.valueOf(modelo.getValueAt(fila, 0));
            v1 = arcArchivoVehiculo.buscarVehiculoChasis(a);
            txtMarca.setText(v1.getMarca());
            txtModelo.setText(v1.getModelo());
            txtPlaca.setText(v1.getPlaca());
            txtTipoMotor.setText(v1.getTipoMotor());
            txtChasis.setText(v1.getChasis());
            txtCilindro.setText(String.valueOf(v1.getCilindraje()));
            txtNumeroP.setText(String.valueOf(v1.getNumeroPuerta()));
            txtFabricacion.setText(String.valueOf(v1.getAñoFabricacion()));
            txtPrecio.setText(String.valueOf(v1.getPrecio()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccionar una fila");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void cmbNuevoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuevoColorActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
        
    }//GEN-LAST:event_cmbNuevoColorActionPerformed

    private void cmbNuevoTipoTransmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuevoTipoTransmisionActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
    }//GEN-LAST:event_cmbNuevoTipoTransmisionActionPerformed

    private void cmbNuevaTapiceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuevaTapiceriaActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
    }//GEN-LAST:event_cmbNuevaTapiceriaActionPerformed

    private void cmbNuevaTipoLLantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuevaTipoLLantasActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
    }//GEN-LAST:event_cmbNuevaTipoLLantasActionPerformed

    private void cmbNuevoTipoArosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuevoTipoArosActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
    }//GEN-LAST:event_cmbNuevoTipoArosActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String matriz[][]=new String[listaR.size()][4];
    boolean res=false;
        for(int i=0;i<listaR.size();i++){
    if(listaR.get(i).getNombreP().equalsIgnoreCase(txtBuscarRepuestos.getText())){
    matriz[i][0]=listaR.get(i).getNombreP();
    matriz[i][1]=listaR.get(i).getMarcaP();
    matriz[i][2]=String.valueOf(listaR.get(i).getPrecioP());
    matriz[i][3]=String.valueOf(listaR.get(i).getCantidad());
    res=true;
    }
    }
    if(res==false){
    JOptionPane.showMessageDialog(null, "NO EXISTE !!!");
    
    }
    jtblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
     matriz,
     new String[]{"NOMBRE","MARCA","PRECIO","CANTIDAD"}));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMrActionPerformed
        mostrarDatosInicio();
    }//GEN-LAST:event_btnMrActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model=(DefaultTableModel) jtblRepuestos.getModel();

        String matriz[][]=new String[5][4];
        int index=jtblRepuestos.getSelectedRow();
        for(int i=0;i<listaR.size();i++){
            if(index==i){

                long valor=Long.parseLong( spnCantidadRepuestos.getValue().toString());
                Repuesto rp2=new Repuesto(listaR.get(i).getNombreP(),listaR.get(i).getMarcaP(),listaR.get(i).getPrecioP(),valor);
                listaCarrito.add(rp2);
            }
        }

        int index2=jtblCarritoRespuestos.getSelectedRow();

        for(int i=0;i<listaCarrito.size();i++){
            matriz[i][0]=listaCarrito.get(i).getNombreP();
            matriz[i][1]=listaCarrito.get(i).getMarcaP();
            matriz[i][2]=String.valueOf(listaCarrito.get(i).getPrecioP()*listaCarrito.get(i).getCantidad());
            matriz[i][3]=String.valueOf(listaCarrito.get(i).getCantidad());
            if(index2==i){
                lblNombreR.setText(listaR.get(i).getNombreP());
                lblMarcaRep.setText(listaR.get(i).getMarcaP());
                lblPrecioRep.setText(String.valueOf(listaR.get(i).getPrecioP()));
            }
        }
        total();

        jtblCarritoRespuestos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String[]{"NOMBRE","MARCA","PRECIO","CANTIDAD"}));

    }                                        
    private void total(){
       double total=0; 
     for(int i=0;i<listaCarrito.size();i++){
     
     total=(listaCarrito.get(i).getPrecioP()*listaCarrito.get(i).getCantidad())+total;
     
     }   
    lblTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEliminarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRepActionPerformed
        int index2=jtblCarritoRespuestos.getSelectedRow();
        String matriz[][]=new String[10][4];
       for(int i=0;i<listaCarrito.size();i++){
       if(index2==i){
       listaCarrito.remove(i);
       
       }
        matriz[i][0]=listaCarrito.get(i).getNombreP();
            matriz[i][1]=listaCarrito.get(i).getMarcaP();
            matriz[i][2]=String.valueOf(listaCarrito.get(i).getPrecioP()*listaCarrito.get(i).getCantidad());
            matriz[i][3]=String.valueOf(listaCarrito.get(i).getCantidad());
       
       
       }
       total();

        jtblCarritoRespuestos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String[]{"NOMBRE","MARCA","PRECIO","CANTIDAD"}));
    }//GEN-LAST:event_btnEliminarRepActionPerformed
        public void mostrarDatosInicio() {
        File archivo=null;
        FileReader fr=null;
        BufferedReader br=null;
        try{
        archivo=new File("ArchivoRepuestos.txt");
        fr = new FileReader(archivo);
        br = new BufferedReader(fr);
        String linea;
        while((linea=br.readLine())!=null){
            
         String[] linea2 = linea.split(",");
         Repuesto rep=new Repuesto(linea2[0],linea2[1],Double.parseDouble(linea2[2]),Long.parseLong(linea2[3]));
         listaR.add(rep);
         String matriz[][]=new String[listaR.size()][4];
          for(int i=0;i<listaR.size();i++){
           matriz[i][0]=listaR.get(i).getNombreP();
    matriz[i][1]=listaR.get(i).getMarcaP();
    matriz[i][2]=String.valueOf(listaR.get(i).getPrecioP());
    matriz[i][3]=String.valueOf(listaR.get(i).getCantidad());
              
              
          }
         jtblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
     matriz,
     new String[]{"NOMBRE","MARCA","PRECIO","CANTIDAD"}));
        }
  }catch(Exception e){
       e.printStackTrace();
       
       }finally{
        try{
        fr.close();
        }
        catch(Exception e2){
            e2.printStackTrace();
        }
        }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Comprar;
    private javax.swing.JButton btnAceptarOferta;
    private javax.swing.JButton btnBuscarVehiculo;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnComprarAuto;
    private javax.swing.JButton btnComprarAuto1;
    private javax.swing.JButton btnEliminarRep;
    private javax.swing.JButton btnMr;
    private javax.swing.JButton btnNuevaOferta;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cmbNuevaTapiceria;
    private javax.swing.JComboBox<String> cmbNuevaTipoLLantas;
    private javax.swing.JComboBox<String> cmbNuevoColor;
    private javax.swing.JComboBox<String> cmbNuevoTipoAros;
    private javax.swing.JComboBox<String> cmbNuevoTipoTransmision;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelComprar;
    private javax.swing.JPanel jPanelRepuestos;
    private javax.swing.JPanel jPanelTalleres;
    private javax.swing.JPanel jPanelVender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jtblCarritoRespuestos;
    private javax.swing.JTable jtblListaTalleres;
    private javax.swing.JTable jtblRepuestos;
    private javax.swing.JTable jtblVehiculos;
    private javax.swing.JLabel lblCantidadRepuesto;
    private javax.swing.JLabel lblMarcaRep;
    private javax.swing.JLabel lblMarcaRepuesto;
    private javax.swing.JLabel lblNombreR;
    private javax.swing.JLabel lblPrecioCliente;
    private javax.swing.JLabel lblPrecioOfrecidoConcecionaria;
    private javax.swing.JLabel lblPrecioRep;
    private javax.swing.JLabel lblPrecioRepuesto;
    private javax.swing.JLabel lblPrecioSugeridoVenta;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorAnoFabricacion;
    private javax.swing.JLabel lblValorChasis;
    private javax.swing.JLabel lblValorCilindraje;
    private javax.swing.JLabel lblValorMarca;
    private javax.swing.JLabel lblValorModelo;
    private javax.swing.JLabel lblValorNumeroPuertas;
    private javax.swing.JLabel lblValorPlaca;
    private javax.swing.JLabel lblValorTipoMotor;
    private javax.swing.JLabel lblVentaAnioFabricacion;
    private javax.swing.JLabel lblVentaAros;
    private javax.swing.JLabel lblVentaChasis;
    private javax.swing.JLabel lblVentaCilindraje;
    private javax.swing.JLabel lblVentaColor;
    private javax.swing.JLabel lblVentaLlantas;
    private javax.swing.JLabel lblVentaMarca;
    private javax.swing.JLabel lblVentaModelo;
    private javax.swing.JLabel lblVentaPlaca;
    private javax.swing.JLabel lblVentaPrecio;
    private javax.swing.JLabel lblVentaPuertas;
    private javax.swing.JLabel lblVentaTapiceria;
    private javax.swing.JLabel lblVentaTipoMotor;
    private javax.swing.JLabel lblVentaTransmision;
    private javax.swing.JPanel pnlDetalleVehiculo;
    private javax.swing.JPanel pnlFormularioVenta;
    private javax.swing.JSpinner spnCantidadRepuestos;
    private javax.swing.JTextField txtBuscaMarcaModelo;
    private javax.swing.JTextField txtBuscarRepuestos;
    private javax.swing.JTextField txtBuscarTalleres;
    private javax.swing.JTextField txtChasis;
    private javax.swing.JTextField txtCilindro;
    private javax.swing.JTextField txtFabricacion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumeroP;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioAdmin;
    private javax.swing.JTextField txtPrecioOfertadoCliente;
    private javax.swing.JTextField txtTipoMotor;
    private javax.swing.JTextField txtVentaAnioFab;
    private javax.swing.JTextField txtVentaAros;
    private javax.swing.JTextField txtVentaChasis;
    private javax.swing.JTextField txtVentaCilindraje;
    private javax.swing.JTextField txtVentaColor;
    private javax.swing.JTextField txtVentaLlantas;
    private javax.swing.JTextField txtVentaMarca;
    private javax.swing.JTextField txtVentaMatricula;
    private javax.swing.JTextField txtVentaModelo;
    private javax.swing.JTextField txtVentaMotor;
    private javax.swing.JTextField txtVentaPlaca;
    private javax.swing.JTextField txtVentaPrecio;
    private javax.swing.JTextField txtVentaPuertas;
    private javax.swing.JTextField txtVentaTapiceria;
    private javax.swing.JTextField txtVentaTransmision;
    // End of variables declaration//GEN-END:variables
}
