/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import tallerautomotriz.ArchivoVehiculos;
import tallerautomotriz.Vehiculo;

/**
 *
 * @author Roberson Constante
 */
public class frmPrincipal extends javax.swing.JFrame {

    ArchivoVehiculos arcArchivoVehiculo = new ArchivoVehiculos();
    ArrayList<Vehiculo> lista = new ArrayList<>();
    Vehiculo v1 = new Vehiculo();
    public frmPrincipal() {
        initComponents();
        pnlDetalleVehiculo.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public void mostrarDatos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CHASIS");
        modelo.addColumn("MODELO");
        modelo.addColumn("MARCA");
        modelo.addColumn("PRECIO");
        jtblVehiculos.setModel(modelo);
        String [] datos = new String [4];
        lista = arcArchivoVehiculo.obtenerVehiculo();
        Iterator it = lista.iterator();
        while(it.hasNext()){
            v1 = (Vehiculo) it.next();
            datos[0] = v1.getChasis();
            datos[1] = v1.getModelo();
            datos[2] = v1.getMarca();
            datos[3] = String.valueOf(v1.getPrecio());
            modelo.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelComprar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscaMarcaModelo = new javax.swing.JTextField();
        btnBuscarVehiculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVehiculos = new javax.swing.JTable();
        pnlDetalleVehiculo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblValorMarca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorModelo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblValorTipoMotor = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblValorCilindraje = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblValorNumeroPuertas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblValorAnoFabricacion = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblValorPlaca = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblPrecioCalculado = new javax.swing.JLabel();
        cmbNuevoTipoAros = new javax.swing.JComboBox<String>();
        cmbNuevaTipoLLantas = new javax.swing.JComboBox<String>();
        cmbNuevaTapiceria = new javax.swing.JComboBox<String>();
        cmbNuevoTipoTransmision = new javax.swing.JComboBox<String>();
        cmbNuevoColor = new javax.swing.JComboBox<String>();
        btnComprarAuto = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        lblValorChasis = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelVender = new javax.swing.JPanel();
        pnlFormularioVenta = new javax.swing.JPanel();
        lblVentaMarca = new javax.swing.JLabel();
        lblVentaModelo = new javax.swing.JLabel();
        lblVentaTipoMotor = new javax.swing.JLabel();
        lblVentaCilindraje = new javax.swing.JLabel();
        lblVentaPuertas = new javax.swing.JLabel();
        lblVentaAnioFabricacion = new javax.swing.JLabel();
        lblVentaPlaca = new javax.swing.JLabel();
        btnComprarAuto1 = new javax.swing.JButton();
        lblVentaChasis = new javax.swing.JLabel();
        txtVentaMarca = new javax.swing.JTextField();
        txtVentaModelo = new javax.swing.JTextField();
        txtVentaPlaca = new javax.swing.JTextField();
        txtVentaMotor = new javax.swing.JTextField();
        txtVentaChasis = new javax.swing.JTextField();
        txtVentaCilindraje = new javax.swing.JTextField();
        txtVentaPuertas = new javax.swing.JTextField();
        txtVentaAnioFab = new javax.swing.JTextField();
        lblVentaColor = new javax.swing.JLabel();
        lblVentaTransmision = new javax.swing.JLabel();
        lblVentaTapiceria = new javax.swing.JLabel();
        lblVentaLlantas = new javax.swing.JLabel();
        lblVentaAros = new javax.swing.JLabel();
        lblVentaPrecio = new javax.swing.JLabel();
        txtVentaColor = new javax.swing.JTextField();
        txtVentaTransmision = new javax.swing.JTextField();
        txtVentaTapiceria = new javax.swing.JTextField();
        txtVentaLlantas = new javax.swing.JTextField();
        txtVentaAros = new javax.swing.JTextField();
        txtVentaPrecio = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblPrecioOfrecidoConcecionaria = new javax.swing.JLabel();
        lblPrecioSugeridoVenta = new javax.swing.JLabel();
        lblPrecioCliente = new javax.swing.JLabel();
        btnAceptarOferta = new javax.swing.JButton();
        btnNuevaOferta = new javax.swing.JButton();
        txtPrecioOfertadoCliente = new javax.swing.JTextField();
        btnCancelarVenta = new javax.swing.JButton();
        jPanelTalleres = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarTalleres = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanelRepuestos = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarRepuestos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblRepuestos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblPrecioRepuesto = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        spnCantidadRepuestos = new javax.swing.JSpinner();
        lblCantidadRepuesto = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblCarritoRespuestos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lblMarcaRepuesto = new javax.swing.JLabel();
        lblMarcaRep = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Comprar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Vehículo"));

        jLabel1.setText("Escriba la Marca de vehículo que desea comprar:");

        btnBuscarVehiculo.setText("Buscar");
        btnBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculoActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscaMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnBuscarVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarVehiculo)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblVehiculos);

        pnlDetalleVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Vehículo"));

        jLabel2.setText("Marca");

        jLabel9.setText("Modelo");

        jLabel11.setText("Tipo de motor");

        jLabel13.setText("Cilindraje");

        jLabel15.setText("Número de Puertas ");

        jLabel17.setText("Año de Fabricación");

        jLabel22.setText("Placa");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Características Personalizables"));

        jLabel3.setText("Color");

        jLabel4.setText("Tipo de transmisión");

        jLabel5.setText("Tapicería");

        jLabel7.setText("Tipo de LLantas");

        jLabel8.setText("Tipo de Aros");

        jLabel19.setText("Precio");

        jLabel20.setText("$");

        lblPrecioCalculado.setText("0.0");

        cmbNuevoTipoAros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Niquelados", "Estándar", "Aluminio" }));

        cmbNuevaTipoLLantas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Llantas de carrera", "Llantas todo terreno", "Llantas estándar" }));

        cmbNuevaTapiceria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuero", "Tela", "Fibras" }));

        cmbNuevoTipoTransmision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automática", "Manual" }));

        cmbNuevoColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amarillo", "Azul", "Blanco", "Gris", "Rojo", "Vino", "Negro", " ", " " }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioCalculado))
                            .addComponent(cmbNuevoColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNuevoTipoTransmision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNuevaTapiceria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNuevaTipoLLantas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNuevoTipoAros, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoTipoTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevaTapiceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevaTipoLLantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoTipoAros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioCalculado)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnComprarAuto.setText("Comprar Vehículo");
        btnComprarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAutoActionPerformed(evt);
            }
        });

        jLabel24.setText("Chasis");

        javax.swing.GroupLayout pnlDetalleVehiculoLayout = new javax.swing.GroupLayout(pnlDetalleVehiculo);
        pnlDetalleVehiculo.setLayout(pnlDetalleVehiculoLayout);
        pnlDetalleVehiculoLayout.setHorizontalGroup(
            pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel11))
                                .addGap(180, 180, 180)
                                .addComponent(lblValorAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblValorTipoMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorNumeroPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorChasis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValorCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(320, Short.MAX_VALUE))
                    .addGroup(pnlDetalleVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 241, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleVehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprarAuto)
                .addGap(202, 202, 202))
        );
        pnlDetalleVehiculoLayout.setVerticalGroup(
            pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleVehiculoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(lblValorMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(lblValorModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(lblValorTipoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(lblValorChasis, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblValorCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorNumeroPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(lblValorAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarAuto)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Resultados");

        jLabel10.setText("Pare ver mayor detalles seleccionar la fila del vehículo");

        javax.swing.GroupLayout jPanelComprarLayout = new javax.swing.GroupLayout(jPanelComprar);
        jPanelComprar.setLayout(jPanelComprarLayout);
        jPanelComprarLayout.setHorizontalGroup(
            jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(pnlDetalleVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComprarLayout.setVerticalGroup(
            jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetalleVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelComprarLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelComprar, "card2");

        pnlFormularioVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vehiculo"));

        lblVentaMarca.setText("Marca");

        lblVentaModelo.setText("Modelo");

        lblVentaTipoMotor.setText("Tipo de motor");

        lblVentaCilindraje.setText("Cilindraje");

        lblVentaPuertas.setText("Número de Puertas ");

        lblVentaAnioFabricacion.setText("Año de Fabricación");

        lblVentaPlaca.setText("Placa");

        btnComprarAuto1.setText("Registrar Vehiculo Para Venta");
        btnComprarAuto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAuto1ActionPerformed(evt);
            }
        });

        lblVentaChasis.setText("Chasis");

        txtVentaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentaMarcaActionPerformed(evt);
            }
        });

        lblVentaColor.setText("Color");

        lblVentaTransmision.setText("Tipo de transmisión");

        lblVentaTapiceria.setText("Tapicería");

        lblVentaLlantas.setText("Tipo de LLantas");

        lblVentaAros.setText("Tipo de Aros");

        lblVentaPrecio.setText("Precio");

        javax.swing.GroupLayout pnlFormularioVentaLayout = new javax.swing.GroupLayout(pnlFormularioVenta);
        pnlFormularioVenta.setLayout(pnlFormularioVentaLayout);
        pnlFormularioVentaLayout.setHorizontalGroup(
            pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaMarca)
                    .addComponent(lblVentaModelo)
                    .addComponent(lblVentaPlaca)
                    .addComponent(lblVentaTipoMotor)
                    .addComponent(lblVentaChasis)
                    .addComponent(lblVentaCilindraje)
                    .addComponent(lblVentaPuertas)
                    .addComponent(lblVentaAnioFabricacion)
                    .addComponent(lblVentaAros)
                    .addComponent(lblVentaColor)
                    .addComponent(lblVentaTransmision)
                    .addComponent(lblVentaTapiceria)
                    .addComponent(lblVentaPrecio))
                .addGap(87, 87, 87)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVentaMarca)
                    .addComponent(txtVentaModelo)
                    .addComponent(txtVentaPlaca)
                    .addComponent(txtVentaMotor)
                    .addComponent(txtVentaChasis)
                    .addComponent(txtVentaCilindraje)
                    .addComponent(txtVentaPuertas)
                    .addComponent(txtVentaAnioFab)
                    .addComponent(txtVentaColor)
                    .addComponent(txtVentaTransmision)
                    .addComponent(txtVentaTapiceria)
                    .addComponent(txtVentaLlantas)
                    .addComponent(txtVentaAros)
                    .addComponent(txtVentaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnComprarAuto1))
                    .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVentaLlantas)))
                .addGap(0, 166, Short.MAX_VALUE))
        );
        pnlFormularioVentaLayout.setVerticalGroup(
            pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioVentaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioVentaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtVentaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVentaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaModelo)
                    .addComponent(txtVentaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaPlaca)
                    .addComponent(txtVentaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaTipoMotor)
                    .addComponent(txtVentaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaChasis)
                    .addComponent(txtVentaChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVentaCilindraje)
                    .addComponent(txtVentaCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaPuertas)
                    .addComponent(txtVentaPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaAnioFabricacion)
                    .addComponent(txtVentaAnioFab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaColor)
                    .addComponent(txtVentaColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaTransmision)
                    .addComponent(txtVentaTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaTapiceria)
                    .addComponent(txtVentaTapiceria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaLlantas)
                    .addComponent(txtVentaLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaAros)
                    .addComponent(txtVentaAros, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVentaPrecio)
                    .addComponent(txtVentaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnComprarAuto1))
        );

        lblPrecioOfrecidoConcecionaria.setText("Precio Estimado del vehiculo:");

        lblPrecioCliente.setText("Precio Ofrecido Por el cliente:");

        btnAceptarOferta.setText("Aceptar");
        btnAceptarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarOfertaActionPerformed(evt);
            }
        });

        btnNuevaOferta.setText("Ofertar");
        btnNuevaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaOfertaActionPerformed(evt);
            }
        });

        txtPrecioOfertadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioOfertadoClienteActionPerformed(evt);
            }
        });

        btnCancelarVenta.setText("Cancelar");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioCliente)
                            .addComponent(lblPrecioOfrecidoConcecionaria))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrecioSugeridoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecioOfertadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAceptarOferta)
                        .addGap(30, 30, 30)
                        .addComponent(btnNuevaOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnCancelarVenta)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPrecioOfrecidoConcecionaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioSugeridoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioCliente)
                    .addComponent(txtPrecioOfertadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarOferta)
                    .addComponent(btnNuevaOferta)
                    .addComponent(btnCancelarVenta)))
        );

        javax.swing.GroupLayout jPanelVenderLayout = new javax.swing.GroupLayout(jPanelVender);
        jPanelVender.setLayout(jPanelVenderLayout);
        jPanelVenderLayout.setHorizontalGroup(
            jPanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormularioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanelVenderLayout.setVerticalGroup(
            jPanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenderLayout.createSequentialGroup()
                .addGroup(jPanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVenderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlFormularioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVenderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelVender, "card3");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Talleres"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setText("Listar Talleres:");

        txtBuscarTalleres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarTalleresActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addComponent(txtBuscarTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtBuscarTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTalleresLayout = new javax.swing.GroupLayout(jPanelTalleres);
        jPanelTalleres.setLayout(jPanelTalleresLayout);
        jPanelTalleresLayout.setHorizontalGroup(
            jPanelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(711, Short.MAX_VALUE))
        );
        jPanelTalleresLayout.setVerticalGroup(
            jPanelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(736, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTalleres, "card4");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Repuestos"));

        jLabel14.setText("Buscar Repuestos");

        jButton3.setText("Buscar");

        jtblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblRepuestos);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(57, 57, 57)
                .addComponent(txtBuscarRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBuscarRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setText("Precio");

        jLabel18.setText("Nombre:");

        lblCantidadRepuesto.setText("Cantidad:");

        jtblCarritoRespuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtblCarritoRespuestos);

        jButton4.setText("Comprar");

        lblMarcaRepuesto.setText("Marca:");

        jButton5.setText("Añadir A Carrito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(lblMarcaRepuesto))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblMarcaRep, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPrecioRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblCantidadRepuesto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnCantidadRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCantidadRepuesto)
                                .addComponent(spnCantidadRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarcaRepuesto)
                            .addComponent(lblPrecioRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMarcaRep, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );

        javax.swing.GroupLayout jPanelRepuestosLayout = new javax.swing.GroupLayout(jPanelRepuestos);
        jPanelRepuestos.setLayout(jPanelRepuestosLayout);
        jPanelRepuestosLayout.setHorizontalGroup(
            jPanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanelRepuestosLayout.setVerticalGroup(
            jPanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(645, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelRepuestos, "card5");

        jMenu1.setText("Vehículos ");

        Comprar.setText("Compra");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        jMenu1.add(Comprar);

        jMenuItem1.setText("Venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Servicio Técnico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Respuestos");

        jMenuItem4.setText("compra de Repuestos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
       jPanelVender.setVisible(false);
       jPanelTalleres.setVisible(false);
       jPanelComprar.setVisible(true);
       jPanelRepuestos.setVisible(false);
       mostrarDatos();
    }//GEN-LAST:event_ComprarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lblValorMarca.setText("");
        lblValorModelo.setText("");
        lblValorPlaca.setText("");
        lblValorTipoMotor.setText("");
        lblValorChasis.setText("");
        lblValorCilindraje.setText("");
        lblValorNumeroPuertas.setText("");
        lblValorAnoFabricacion.setText("");       
        pnlDetalleVehiculo.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculoActionPerformed
      
         pnlDetalleVehiculo.setVisible(true);
         arcArchivoVehiculo.buscarVehiculo(txtBuscaMarcaModelo.getText());
         
    }//GEN-LAST:event_btnBuscarVehiculoActionPerformed

    private void btnComprarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAutoActionPerformed
        new frmDatosPago().setVisible(true);
    }//GEN-LAST:event_btnComprarAutoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       jPanelVender.setVisible(false);
       jPanelTalleres.setVisible(false);
       jPanelComprar.setVisible(false);
       jPanelRepuestos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnComprarAuto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAuto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarAuto1ActionPerformed

    private void txtVentaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentaMarcaActionPerformed

    private void btnAceptarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarOfertaActionPerformed

    private void btnNuevaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaOfertaActionPerformed

    private void txtPrecioOfertadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioOfertadoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioOfertadoClienteActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanelComprar.setVisible(false);
        jPanelTalleres.setVisible(false);
        jPanelVender.setVisible(true);
        jPanelRepuestos.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtBuscarTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarTalleresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarTalleresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         jPanelVender.setVisible(false);
       jPanelTalleres.setVisible(true);
       jPanelComprar.setVisible(false);
       jPanelRepuestos.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Comprar;
    private javax.swing.JButton btnAceptarOferta;
    private javax.swing.JButton btnBuscarVehiculo;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnComprarAuto;
    private javax.swing.JButton btnComprarAuto1;
    private javax.swing.JButton btnNuevaOferta;
    private javax.swing.JComboBox<String> cmbNuevaTapiceria;
    private javax.swing.JComboBox<String> cmbNuevaTipoLLantas;
    private javax.swing.JComboBox<String> cmbNuevoColor;
    private javax.swing.JComboBox<String> cmbNuevoTipoAros;
    private javax.swing.JComboBox<String> cmbNuevoTipoTransmision;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelComprar;
    private javax.swing.JPanel jPanelRepuestos;
    private javax.swing.JPanel jPanelTalleres;
    private javax.swing.JPanel jPanelVender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jtblCarritoRespuestos;
    private javax.swing.JTable jtblRepuestos;
    private javax.swing.JTable jtblVehiculos;
    private javax.swing.JLabel lblCantidadRepuesto;
    private javax.swing.JLabel lblMarcaRep;
    private javax.swing.JLabel lblMarcaRepuesto;
    private javax.swing.JLabel lblPrecioCalculado;
    private javax.swing.JLabel lblPrecioCliente;
    private javax.swing.JLabel lblPrecioOfrecidoConcecionaria;
    private javax.swing.JLabel lblPrecioRepuesto;
    private javax.swing.JLabel lblPrecioSugeridoVenta;
    private javax.swing.JLabel lblValorAnoFabricacion;
    private javax.swing.JLabel lblValorChasis;
    private javax.swing.JLabel lblValorCilindraje;
    private javax.swing.JLabel lblValorMarca;
    private javax.swing.JLabel lblValorModelo;
    private javax.swing.JLabel lblValorNumeroPuertas;
    private javax.swing.JLabel lblValorPlaca;
    private javax.swing.JLabel lblValorTipoMotor;
    private javax.swing.JLabel lblVentaAnioFabricacion;
    private javax.swing.JLabel lblVentaAros;
    private javax.swing.JLabel lblVentaChasis;
    private javax.swing.JLabel lblVentaCilindraje;
    private javax.swing.JLabel lblVentaColor;
    private javax.swing.JLabel lblVentaLlantas;
    private javax.swing.JLabel lblVentaMarca;
    private javax.swing.JLabel lblVentaModelo;
    private javax.swing.JLabel lblVentaPlaca;
    private javax.swing.JLabel lblVentaPrecio;
    private javax.swing.JLabel lblVentaPuertas;
    private javax.swing.JLabel lblVentaTapiceria;
    private javax.swing.JLabel lblVentaTipoMotor;
    private javax.swing.JLabel lblVentaTransmision;
    private javax.swing.JPanel pnlDetalleVehiculo;
    private javax.swing.JPanel pnlFormularioVenta;
    private javax.swing.JSpinner spnCantidadRepuestos;
    private javax.swing.JTextField txtBuscaMarcaModelo;
    private javax.swing.JTextField txtBuscarRepuestos;
    private javax.swing.JTextField txtBuscarTalleres;
    private javax.swing.JTextField txtPrecioOfertadoCliente;
    private javax.swing.JTextField txtVentaAnioFab;
    private javax.swing.JTextField txtVentaAros;
    private javax.swing.JTextField txtVentaChasis;
    private javax.swing.JTextField txtVentaCilindraje;
    private javax.swing.JTextField txtVentaColor;
    private javax.swing.JTextField txtVentaLlantas;
    private javax.swing.JTextField txtVentaMarca;
    private javax.swing.JTextField txtVentaModelo;
    private javax.swing.JTextField txtVentaMotor;
    private javax.swing.JTextField txtVentaPlaca;
    private javax.swing.JTextField txtVentaPrecio;
    private javax.swing.JTextField txtVentaPuertas;
    private javax.swing.JTextField txtVentaTapiceria;
    private javax.swing.JTextField txtVentaTransmision;
    // End of variables declaration//GEN-END:variables
}
